### ISSUE TITLE
Empty content when calling webhook with custom alert

### ISSUE THREAD

**Issue by scubix** [soranoo/TradingView-Free-Webhook-Alerts#1]
The content seems to be empty :
08-02-2022 19:30:05   |  INFO     | Sending webhook alert<Alert:  DOT webhook>..., content:
08-02-2022 19:30:05   |  OK       | Sent webhook alert successfully!

The service that received the call logged this :

[19:30:05.578] [INFO]  ""

When looking at the email in my GMail account, the data is there (json string).

**Comment by soranoo** [comment]
Can I have your JSON string?

**Comment by scubix** [comment]
> Can I have your JSON string?

{"c": "BUY", "t":"jgsTR36s14f#f$yh$fs258uee4!8H"}

I think it is happening because I choose "Send Email". The email that was received is a HTML email and has no regular text content. I changed my TV settings now to use "Send email-to-SMS", but so far no new alert has triggered yet.

**Comment by scubix** [comment]
I can confirm it works fine with "Send email-to-SMS"

**Comment by soranoo** [comment]
"Send Email" will be working in the next update. Thank you for your support~ 😄
