### ISSUE TITLE
'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Andreymyski** [soranoo/TradingView-Free-Webhook-Alerts#11]
Hello. I did everything according to your instructions, but in the end I get the error "Here an error has occurred, reason: 'NoneType' object has no attribute 'replace'" 
Tell me what the problem might be, thank you.

![8bc8ca5e5fed7d59a770ca218bd9dfe1](https://user-images.githubusercontent.com/116179517/197501792-392d83b0-9b39-4d8c-a99c-e8c74b909d9a.jpg)

**Comment by soranoo** [comment]
Please input your email address and login password in the file "config.toml" (`email_address` & `login_password`) instead of directly putting them into the script.

**Comment by soranoo** [comment]
Don't forget to change your email password in order to protect your account from others. Please blur/hide your sensitive information such as passwords before uploading any image.
