### ISSUE TITLE
 #cloud based workflow server #resolved gimail integration requirement in tradingview free webhook alert #pipedream 

### ISSUE THREAD

**Issue by Priyanshu-raj95** [soranoo/TradingView-Free-Webhook-Alerts#15]
Hiii  @soranoo 
   
  write now we are sending free webhook alert   required  python , also in email google had band the 3rd pary integration to integrate it only allow to integrate user who has  Google Cloud  , personal  required required  in email there is a problem it may be ban due to reasons . 

we can **over come these **problems**** in pipedream it is open source **free** cloud based workflow provider .  
1st   login in **_pipedream_** 
2nd create a **workflow**  [https://pipedream.com/@/new/build](url)
3rd use email as a **trigger** copy it and paste in email to sms as a trigger in tv alert.  it will  send otp to pipedream work flow  body 
     text 
   now were successfully connected pipedream email into alert . as  alert trigger  message send to email and we can **xtract the path** and 
   send post request  
4th extract the value requires to send post webhook request copied the path and paste in python  code step 
5th in  a work flow you can also connect telegram http post request , and discord  to send messages 
 5th deploy now your  work flow has successfully created on cloud server  it works 24 x 7 

bro i dont know python to send post requests with paylods  . i read  pipedream documentaion it has written there  . i cant understand much  

these steps make us very light to use Trading view free webhook

_Originally posted by @Priyanshu-raj95 in https://github.com/soranoo/TradingView-Free-Webhook-Alerts/discussions/14_

**Comment by soranoo** [comment]
The pipedream version is **NOW** under development. Thank you for your suggestion.

Your suggestion will be documented in the documentation after the code is completed.
