### ISSUE TITLE
src.helpers not available

### ISSUE THREAD

**Issue by Kclemen** [soranoo/TradingView-Free-Webhook-Alerts#33]
I updated today and suddenly receive following error message:

from .helpers import (
ModuleNotFoundError: No module named 'src.helpers'

**Comment by soranoo** [comment]
May I see your log? (inside the `logs` folder) or provide further info about how you activated the error.

**Comment by Kclemen** [comment]
The log does not contain any information because the script can not run.
The error started today when I downloaded the entire github folder and tried to run main.py.

So, I downloaded the github as a zip and extracted. Than installed requirements and tried to run main.py.

**Comment by soranoo** [comment]
Can you provide some screenshots?
