### ISSUE TITLE
it stops suddenly

### ISSUE THREAD

**Issue by matts93** [soranoo/TradingView-Free-Webhook-Alerts#34]
after a while it stops abruptly, as if I had stopped it manually
but it is not possible it is on an online vps

the method I'm using is the standard one
the latest log is this:
```
06-04-2023 20:50:10 | DEBUG     | PROCESSING: Email UID<285> from noreply@tradingview.com
06-04-2023 20:50:10 | INFO      | Sending webhook alert<Alert: Lorentzian Classification (close, 8, 2000, 5, 1, -0.1, 20,
 RSI, 14, 1,
 WT, 10, 11, CCI, 20, 1, ADX, 20, 2, RSI, 9, 1, 200, 200, 8, 8, 25, 2,
 0): qualsiasi funzione alert()>, content: {"list_signal_id": "7", "platform_id": "1", "simbolo": "AUDCAD", "direzione": "BUY", "prezzo_entrata": "OPEN", "TP_1": "0", "TP_2": "0", "TP_3": "0", "SL": "0"}
06-04-2023 20:50:10 | OK        | Sent webhook alert successfully!
06-04-2023 20:50:10 | INFO      | The whole process taken 8.525s.
```

then this appears:

`
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│                                                                              │
│ /home/xrdpuser/Desktop/TradingView/main.py:217 in main                       │
│                                                                              │
│   214 │                                                                      │
│   215 │   def main(self):                                                    │
│   216 │   │   try:                                                           │
│ ❱ 217 │   │   │   self.start()                                               │
│   218 │   │   except KeyboardInterrupt:                                      │
│   219 │   │   │   log.warning("The program has been stopped by user.")       │
│   220 │   │   │   shutdown()                                                 │
│ /home/xrdpuser/Desktop/TradingView/main.py:213 in start                      │
│                                                                              │
│   210 │   │                                                                  │
│   211 │   │   # Start listening to the inbox                                 │
│   212 │   │   log.info(f"Listening to IMAP server({imap_server_address})..." │
│ ❱ 213 │   │   el.listen(-1, process_func=self.on_email_received)             │
│   214 │                                                                      │
│   215 │   def main(self):                                                    │
│   216 │   │   try:                                                           │
│                                                                              │
│ /home/xrdpuser/Desktop/TradingView/src/email_listener/__init__.py:379 in     │
│ listen                                                                       │
│                                                                              │
│   376 │   │   # Run until the timeout is reached                             │
│   377 │   │   if timeout == -1:                                              │
│   378 │   │   │   while True:                                                │
│ ❱ 379 │   │   │   │   self.__idle(timeout=update_frequency, process_func=pro │
│   380 │   │   else:                                                          │
│   381 │   │   │   while (get_time() < outer_timeout):                        │
│   382 │   │   │   │   self.__idle(timeout=update_frequency, process_func=pro │
│                                                                              │
│ /home/xrdpuser/Desktop/TradingView/src/email_listener/__init__.py:428 in     │
│ __idle                                                                       │
│                                                                              │
│   425 │   │   │   # If there is a response                                   │
│   426 │   │   │   if (responses):                                            │
│   427 │   │   │   │   # Suspend the idling                                   │
│ ❱ 428 │   │   │   │   self.server.idle_done()                                │
│   429 │   │   │   │   # Process the new emails                               │
│   430 │   │   │   │   msgs = self.scrape(move=move, unread=unread, delete=de │
│   431 │   │   │   │   # Run the process function                             │
│                                                                              │
│ /home/xrdpuser/.local/lib/python3.10/site-packages/imapclient/imapclient.py: │
│ 176 in wrapper                                                               │
│                                                                              │
│    173 │   │   │   │   raise exceptions.CapabilityError(                     │
│    174 │   │   │   │   │   "Server does not support {} capability".format(ca │
│    175 │   │   │   │   )                                                     │
│ ❱  176 │   │   │   return func(client, *args, **kwargs)                      │
│    177 │   │                                                                 │
│    178 │   │   return wrapper                                                │
│    179                                                                       │
│                                                                              │
│ /home/xrdpuser/.local/lib/python3.10/site-packages/imapclient/imapclient.py: │
│ 992 in idle_done                                                             │
│                                                                              │
│    989 │   │   """                                                           │
│    990 │   │   logger.debug("< DONE")                                        │
│    991 │   │   self._imap.send(b"DONE\r\n")                                  │
│ ❱  992 │   │   return self._consume_until_tagged_response(self._idle_tag, "I │
│    993 │                                                                     │
│    994 │   def folder_status(self, folder, what=None):                       │
│    995 │   │   """Return the status of *folder*.                             │
│                                                                              │
│ /home/xrdpuser/.local/lib/python3.10/site-packages/imapclient/imapclient.py: │
│ 1627 in _consume_until_tagged_response                                       │
│                                                                              │
│   1624 │   │   tagged_commands = self._imap.tagged_commands                  │
│   1625 │   │   resps = []                                                    │
│   1626 │   │   while True:                                                   │
│ ❱ 1627 │   │   │   line = self._imap._get_response()                         │
│   1628 │   │   │   if tagged_commands[tag]:                                  │
│   1629 │   │   │   │   break                                                 │
│   1630 │   │   │   resps.append(_parse_untagged_response(line))              │
│                                                                              │
│ /usr/lib/python3.10/imaplib.py:1075 in _get_response                         │
│                                                                              │
│   1072 │   │   # Returns None for continuation responses,                    │
│   1073 │   │   # otherwise first response line received.                     │
│   1074 │   │                                                                 │
│ ❱ 1075 │   │   resp = self._get_line()                                       │
│   1076 │   │                                                                 │
│   1077 │   │   # Command completion response?                                │
│   1078                                                                       │
│                                                                              │
│ /usr/lib/python3.10/imaplib.py:1185 in _get_line                             │
│                                                                              │
│   1182 │   │                                                                 │
│   1183 │   │   line = self.readline()                                        │
│   1184 │   │   if not line:                                                  │
│ ❱ 1185 │   │   │   raise self.abort('socket error: EOF')                     │
│   1186 │   │                                                                 │
│   1187 │   │   # Protocol mandates all lines terminated by CRLF              │
│   1188 │   │   if not line.endswith(b'\r\n'):                                │
╰──────────────────────────────────────────────────────────────────────────────╯
abort: socket error: EOF

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│                                                                              │
│ /home/xrdpuser/Desktop/TradingView/main.py:340 in <module>                   │
│                                                                              │
│   337 │   if(config_version != expect_config_version):                       │
│   338 │   │   log.error(f"The config file is outdated. Please update it to t │
│   339 │   │   shutdown()                                                     │
│ ❱ 340 │   main()                                                             │
│ /home/xrdpuser/Desktop/TradingView/main.py:328 in main                       │
│                                                                              │
│   325 │   if discord_log:                                                    │
│   326 │   │   log.addHandler(DiscordLogHandler())                            │
│   327 │   if mode_traditional:                                               │
│ ❱ 328 │   │   EmailSignalExtraction().main()                                 │
│   329 │   else:                                                              │
│   330 │   │   NgrokSignalRedirect().main()                                   │
│   331                                                                        │
│                                                                              │
│ /home/xrdpuser/Desktop/TradingView/main.py:227 in main                       │
│                                                                              │
│   224 │   │   │   │   shutdown()                                             │
│   225 │   │   │   log.warning(f"The program will try to reconnect after {ima │
│   226 │   │   │   time.sleep(imap_auto_reconnect_wait)                       │
│ ❱ 227 │   │   │   self.start()                                               │
│   228                                                                        │
│   229 class NgrokSignalRedirect:                                             │
│   230 │   class _EventID:                                                    │
│                                                                              │
│ /home/xrdpuser/Desktop/TradingView/main.py:213 in start                      │
│                                                                              │
│   210 │   │                                                                  │
│   211 │   │   # Start listening to the inbox                                 │
│   212 │   │   log.info(f"Listening to IMAP server({imap_server_address})..." │
│ ❱ 213 │   │   el.listen(-1, process_func=self.on_email_received)             │
│   214 │                                                                      │
│   215 │   def main(self):                                                    │
│   216 │   │   try:                                                           │
│                                                                              │
│ /home/xrdpuser/Desktop/TradingView/src/email_listener/__init__.py:379 in     │
│ listen                                                                       │
│                                                                              │
│   376 │   │   # Run until the timeout is reached                             │
│   377 │   │   if timeout == -1:                                              │
│   378 │   │   │   while True:                                                │
│ ❱ 379 │   │   │   │   self.__idle(timeout=update_frequency, process_func=pro │
│   380 │   │   else:                                                          │
│   381 │   │   │   while (get_time() < outer_timeout):                        │
│   382 │   │   │   │   self.__idle(timeout=update_frequency, process_func=pro │
│                                                                              │
│ /home/xrdpuser/Desktop/TradingView/src/email_listener/__init__.py:428 in     │
│ __idle                                                                       │
│                                                                              │
│   425 │   │   │   # If there is a response                                   │
│   426 │   │   │   if (responses):                                            │
│   427 │   │   │   │   # Suspend the idling                                   │
│ ❱ 428 │   │   │   │   self.server.idle_done()                                │
│   429 │   │   │   │   # Process the new emails                               │
│   430 │   │   │   │   msgs = self.scrape(move=move, unread=unread, delete=de │
│   431 │   │   │   │   # Run the process function                             │
│                                                                              │
│ /home/xrdpuser/.local/lib/python3.10/site-packages/imapclient/imapclient.py: │
│ 176 in wrapper                                                               │
│                                                                              │
│    173 │   │   │   │   raise exceptions.CapabilityError(                     │
│    174 │   │   │   │   │   "Server does not support {} capability".format(ca │
│    175 │   │   │   │   )                                                     │
│ ❱  176 │   │   │   return func(client, *args, **kwargs)                      │
│    177 │   │                                                                 │
│    178 │   │   return wrapper                                                │
│    179                                                                       │
│                                                                              │
│ /home/xrdpuser/.local/lib/python3.10/site-packages/imapclient/imapclient.py: │
│ 992 in idle_done                                                             │
│                                                                              │
│    989 │   │   """                                                           │
│    990 │   │   logger.debug("< DONE")                                        │
│    991 │   │   self._imap.send(b"DONE\r\n")                                  │
│ ❱  992 │   │   return self._consume_until_tagged_response(self._idle_tag, "I │
│    993 │                                                                     │
│    994 │   def folder_status(self, folder, what=None):                       │
│    995 │   │   """Return the status of *folder*.                             │
│                                                                              │
│ /home/xrdpuser/.local/lib/python3.10/site-packages/imapclient/imapclient.py: │
│ 1627 in _consume_until_tagged_response                                       │
│                                                                              │
│   1624 │   │   tagged_commands = self._imap.tagged_commands                  │
│   1625 │   │   resps = []                                                    │
│   1626 │   │   while True:                                                   │
│ ❱ 1627 │   │   │   line = self._imap._get_response()                         │
│   1628 │   │   │   if tagged_commands[tag]:                                  │
│   1629 │   │   │   │   break                                                 │
│   1630 │   │   │   resps.append(_parse_untagged_response(line))              │
│                                                                              │
│ /usr/lib/python3.10/imaplib.py:1075 in _get_response                         │
│                                                                              │
│   1072 │   │   # Returns None for continuation responses,                    │
│   1073 │   │   # otherwise first response line received.                     │
│   1074 │   │                                                                 │
│ ❱ 1075 │   │   resp = self._get_line()                                       │
│   1076 │   │                                                                 │
│   1077 │   │   # Command completion response?                                │
│   1078                                                                       │
│                                                                              │
│ /usr/lib/python3.10/imaplib.py:1185 in _get_line                             │
│                                                                              │
│   1182 │   │                                                                 │
│   1183 │   │   line = self.readline()                                        │
│   1184 │   │   if not line:                                                  │
│ ❱ 1185 │   │   │   raise self.abort('socket error: EOF')                     │
│   1186 │   │                                                                 │
│   1187 │   │   # Protocol mandates all lines terminated by CRLF              │
│   1188 │   │   if not line.endswith(b'\r\n'):                                │
╰──────────────────────────────────────────────────────────────────────────────╯
abort: socket error: EOF
`

**Comment by soranoo** [comment]
Have you set the `imap_auto_reconnect` to true in the `config.toml` file? The program should reconnect automatically if there any error occurs.

By the way, it is not recommended to use the traditional version due to the instability and the slow reaction speed.

**Comment by matts93** [comment]
# auto reconnect to IMAP server when disconnected
imap_auto_reconnect = true

# wait time (seconds) before reconnecting to IMAP server
imap_auto_reconnect_wait = 10

Are the other options all free with limitations? if you don't pay?

**Comment by soranoo** [comment]
Sorry, I do not really understand what you mean.

If you want to change to another version please read the following documents (tutorial videos also available):
- [Local (ngrok)](https://github.com/soranoo/TradingView-Free-Webhook-Alerts/blob/main/docs/gettingstarted.md#2-ngrok-version)
or
- [Cloud pipdream](https://github.com/soranoo/TradingView-Free-Webhook-Alerts/blob/main/docs/cloud-versions/pipedream/pipedream.md)
