### ISSUE TITLE
Previous alerts are being send out again

### ISSUE THREAD

**Issue by scubix** [soranoo/TradingView-Free-Webhook-Alerts#4]
When receiving an alert, previous alerts were send out again as well :

17-02-2022 14:30:29   |  INFO     | Sending webhook alert<Alert: BTC Trade>, content: {'c': 'STOP', 't': '1234567890'}
17-02-2022 14:30:29   |  OK       | Sent webhook alert successfully!
17-02-2022 14:30:29   |  INFO     | The whole process taken 21.792s.
17-02-2022 14:30:30   |  INFO     | Sending webhook alert<Alert: BTC Trade>, content: {'c': 'SELL', 't': '1234567890'}
17-02-2022 14:30:30   |  OK       | Sent webhook alert successfully!
17-02-2022 14:30:30   |  INFO     | The whole process taken 178215.88s.
17-02-2022 14:30:32   |  INFO     | Sending webhook alert<Alert: BTC Trade>, content: {'c': 'BUY', 't': '1234567890'}
17-02-2022 14:30:32   |  OK       | Sent webhook alert successfully!
17-02-2022 14:30:32   |  INFO     | The whole process taken 227609.068s.
17-02-2022 14:30:33   |  INFO     | Sending webhook alert<Alert: BTC Trade>, content: {'c': 'SELL', 't': '1234567890'}
17-02-2022 14:30:33   |  OK       | Sent webhook alert successfully!
17-02-2022 14:30:33   |  INFO     | The whole process taken 253824.331s.

The process time is also completely wrong because they were old alerts.

**Comment by soranoo** [comment]
After many tests, I did not encounter the relevant situation but I will try to fix it as possible as I can. I hope the next update will help with the problem.
