### ISSUE TITLE
Less Secure Access Google, no longer available

### ISSUE THREAD

**Issue by Pest202** [soranoo/TradingView-Free-Webhook-Alerts#5]
They removed the less secure access option, is there a workaround, and which is the next recommended email suitable for this use?
https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4MCqIEkbXl_ukdC2ZL2bnZaSQpOcJ19D7BgASIy9DjHyJqYKXALxkdohRy5PbTDt8TH-3j8cfzOHouBGjz4mHzbd16JCg

thank you for your time

**Comment by soranoo** [comment]
Thank you for your report.
**Hotmail** & **Outlook** are still working perfectly.
I will keep looking for other better IMAP services. Please feel free to contact me if you have any suggestions.

For Hotmail & Outlook:
IMAP server address: **outlook.office365.com**
IMAP server port: **993**

Example(`config.toml`):
```
# -----------* Email Service *-----------
email_address = "YourEmail@hotmail.com / YourEmail@outlook.com"
login_password = "YourPassword"
imap_server_address = "outlook.office365.com"
imap_server_port = 993
```

The document and example will be updated soon...

You can update your TradingView `Email-To-SMS` by following this [page](https://www.tradingview.com/support/solutions/43000474398-how-to-change-the-email-to-sms-address-used-for-alert-notifications/).

**Comment by soranoo** [comment]
Please don't forget to say **YES** in `Let devices and apps use POP`. (located in [`Setting/Mail/Sync email/POP and IMAP`](https://outlook.live.com/mail/0/options/mail/accounts/popImap))

**Comment by Pest202** [comment]
Hi, thank you for the very fast reply, i faced a problem however the email message was received, main.py had no errors but it didn't respond to the email(using email-to-sms)
![Screenshot (539)](https://user-images.githubusercontent.com/110617281/182986076-1273f27c-c387-42d9-a6ad-c0acba825955.png)
(ignore timestamps main.py was reopened and looked the same)
thank you

**Comment by soranoo** [comment]
🤔 Um... I didn't encounter this problem. Restarting the program might help.

**Comment by Pest202** [comment]
> 🤔 Um... I didn't encounter this problem. Restarting the program might help.
It detected the message now, but it shows an error, should i contact the webhook receiver?
![Screenshot (540)](https://user-images.githubusercontent.com/110617281/183076606-bfa7d5a4-b897-4dff-bf48-01d774ccc057.png)

**Comment by soranoo** [comment]
This problem is caused by the `requests` library. A new issue #6 has been opened. I will try to fix the problem ASAP.

**Comment by Pest202** [comment]
> This problem is caused by the `requests` library. A new issue #6 has been opened. I will try to fix the problem ASAP.

main.py, appears to be closing on its own today, tried 2 times to verify. Run as Admin, AV disabled.
kindly let me know if you faced a similar problem

**Comment by soranoo** [comment]
The program will shut down after 10 seconds when there is an error. It is common when IMAP connect fails. Auto reconnect will be added in the coming update.

(You can read through the log file to see what the program really happened.)
