### ISSUE TITLE
Not taking action in bot

### ISSUE THREAD

**Issue by GencKimyasal** [soranoo/TradingView-Free-Webhook-Alerts#60]
My friend, the alert code sent to the e-mail is sent to the webhook, but the bot does not receive any action. If you want, write to me on telegram or discord and I will show you live.

Telegram: @GencKimyasal
Discord: @genckimyasal

**Comment by soranoo** [comment]
Do you mean your targeted platform does nothing to the webhook signal?
May I have the name of your targeted platform?
Which version you are using the pipedream version or the others?

**Comment by GencKimyasal** [comment]
My friend, reach me on one of the two platforms so that I can show you this better, because I turned it into a software directly without using pipedream.

**Comment by GencKimyasal** [comment]
I send the long or short alert code sent to the e-mail to the webhook, but it does not receive any action.

**Comment by soranoo** [comment]
Sorry mate. I am not going to use dc and tg to handle any GitHub communication for some reason.

**Comment by GencKimyasal** [comment]
The version is the same, but the problem is that it forwards the long - short alert code sent to this e-mail to the webhook, but it does not receive any action from the bot.

**Comment by soranoo** [comment]
Sorry, I didn't make it clear. The version means ngrok, traditional and cloud.
