### ISSUE TITLE
ngrok-agent version "2.3.41" is too old

### ISSUE THREAD

**Issue by francovp** [soranoo/TradingView-Free-Webhook-Alerts#66]
**Describe the bug**
When running latest version I get the following error from `pyngrok`

```
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start: Your ngrok-agent version "2.3.41" is too old. The minimum supported agent version for your account is "3.2.0". Please update to a newer version with `ngrok update`, by downloading from https://ngrok.com/download, or by updating your SDK version. Paid accounts are currently excluded from minimum agent version requirements. To begin handling traffic immediately without updating your agent, upgrade to a paid plan: https://dashboard.ngrok.com/billing/subscription.\r\n\r\nERR_NGROK_121\r\n.
```

**To Reproduce**
1. Run `python main.py`
2. See error

**Environment:**
 - OS: MacOS Soloma
 - Python Version: 3.11.7
 - Program Version: local-ngrok

**Additional context**

Bumping `pyngrok` from version `5.2.1` to [`6.1.2`](https://pypi.org/project/pyngrok/6.1.2/) or [`7.1.3`](https://pypi.org/project/pyngrok/7.1.3/) fixed it for me

**Comment by soranoo** [comment]
To resolve it,
1. `pip install --upgrade pyngrok`
or
1. Download the latest `requirements.txt`
2. Remove your old venv (if any)
3. Install the `requirements.txt` again

**Comment by alhaidri** [comment]
`It looks like you are experiencing multiple issues while trying to install ngrok through the APT package manager. The key issue appears to be related to the NVIDIA CUDA repository, which is causing signature verification errors. Here's a step-by-step guide to help you resolve these issues:

### 1. Fix the NVIDIA Repository Errors

First, let's resolve the NVIDIA repository signing issue. You can either add the missing GPG key or temporarily disable the repository to proceed with the ngrok installation.

#### Option A: Add Missing GPG Key

To add the missing GPG key, run the following command:

```bash
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/debian10/x86_64/7fa2af80.pub
```

After adding the GPG key, try updating your package list again:

```bash
sudo apt update
```

#### Option B: Temporarily Disable the NVIDIA Repository

If you prefer, you can temporarily comment out the NVIDIA CUDA repository in your sources list. Open the sources list with a text editor:

```bash
sudo nano /etc/apt/sources.list
```

Look for lines that start with `deb http://developer.download.nvidia.com/compute/cuda` and comment them out by adding a `#` at the beginning of those lines. Save and exit the editor (`Ctrl + O` to save, `Ctrl + X` to exit).

Then, run:

```bash
sudo apt update
```

### 2. Remove Duplicate Entries in Sources List

It seems you have duplicates in your `/etc/apt/sources.list` based on the warnings. You can clean that up by opening the file:

```bash
sudo nano /etc/apt/sources.list
```

Look for duplicate lines and remove or comment out one of each pair. Save and exit once you're done.

### 3. Add the ngrok Repository Again

Now that you've resolved the other issues, add the ngrok repository again if necessary. 

```bash
curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
```

### 4. Update Package List

Run the update command again to refresh the sources:

```bash
sudo apt update
```

### 5. Install ngrok

Finally, attempt to install ngrok again:

```bash
sudo apt install ngrok
```

### 6. Verify the Installation

Once installed, you can verify the installation by checking the version:

```bash
ngrok version
```

### Conclusion

Following these steps should resolve the issues you're facing. If you still encounter errors, please provide the error messages, and we'll continue troubleshooting from there.`
