### ISSUE TITLE
[feat] Bypass exchange region IP ban

### ISSUE THREAD

**Issue by soranoo** [soranoo/TradingView-Free-Webhook-Alerts#69]
### Discussed in https://github.com/soranoo/TradingView-Free-Webhook-Alerts/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **hebe061103** March 18, 2024</sup>
![截图 2024-03-18 14-14-54](https://github.com/soranoo/TradingView-Free-Webhook-Alerts/assets/24790402/2d72bfe0-4a39-4d1f-ba1a-313884a83ead)
</div>

If you are using Pipedream, you may face a service denial problem. It seems there are some of Pipedream's servers are located in restricted areas (eg. USA)

### Solution
- Proxy the webhook request

**Comment by soranoo** [comment]
https://github.com/soranoo/TradingView-Free-Webhook-Alerts?tab=readme-ov-file#question-faq

**Comment by hebe061103** [comment]
是个好想法, 现在的问题是我没有代理,也找不到free代理,即使有也不稳定.我想找个域名自己搭建VPS,创建代理.同样也没有免费的..绕了一圈,发现我还在原地.不如一开始支付td最低套餐来的实际.
现在有两个办法.1.支付TD 2.更换不被限制的交易所

**Comment by soranoo** [comment]
Check out https://www.webshare.io/ .

And please type in English for other future reference.

**Comment by nemagoudar** [comment]
Hi,
I am trying this between Dhan and trading view with ngrok method. I see webhook post request fails with reason as 500 error from Dhan webhook.
Is this may be because of proxy ? Please let us know how to mention proxy server for Dhan.
