### ISSUE TITLE
[Errno 2] No such file or directory: 'config.toml'

### ISSUE THREAD

**Issue by hanliudeepmind** [soranoo/TradingView-Free-Webhook-Alerts#7]
Hello, 
I want to use Free Webhook Alert
But when I follow the steps I face some problems

![image](https://user-images.githubusercontent.com/111733657/185867006-854f6be6-9ba5-4228-a314-e2b992829c3e.png)
![image](https://user-images.githubusercontent.com/111733657/185867712-3a18476e-5532-472e-9de1-dec0a461347f.png)

Not sure what's wrong ><

**Comment by soranoo** [comment]
Thank you for your support.
This problem is caused by the incomplete path of `config.toml`.
This should be ok now.

**Comment by hanliudeepmind** [comment]
Thank you very much!
You are so fast for reply!!

So I have to keep this open right?
![image](https://user-images.githubusercontent.com/111733657/185872460-ed98ef65-a6eb-446b-bbdf-0725b7b73adb.png)

And also if I want to send to another webhook url
what can I do><

**Comment by soranoo** [comment]
Yes, you are right.

You can add another webhook URL inside the `config.toml`.
-example:
```
# --------------* Webhook *--------------
webhook_urls = [
    "Webhook URL 1",
    "Webhook URL 2",
    ]
```

**Comment by hanliudeepmind** [comment]
Sorry for bothering you again><
I set up everything and when alert works I get the mail
also main.py shows that it send to webhook successfully

but the webhook I send to discord has nothing show up

![image](https://user-images.githubusercontent.com/111733657/185928806-2895e125-aa1c-4cc1-9254-d09c48e6b1af.png)
I got the mail
![image](https://user-images.githubusercontent.com/111733657/185928936-47cc699e-38b0-4c9d-abd0-d79fd7f35177.png)
I got the success message from main.py

![image](https://user-images.githubusercontent.com/111733657/185929063-64331201-9e94-4a8a-ad6e-34fe6343805f.png)
but still nothing here@@

![image](https://user-images.githubusercontent.com/111733657/185929175-5c3ed1ff-b2b5-4669-bdd6-bea468c28687.png)
I do connect the webhook copy from discord and paste to "config.toml"
![image](https://user-images.githubusercontent.com/111733657/185929448-441c3471-4a7f-4475-acb9-7c4c9768e0ae.png)

not sure if I miss anything><

**Comment by soranoo** [comment]
To send a message to Discord, you should contain `{"content": "you message"}` in your webhook message.

**Comment by hanliudeepmind** [comment]
Thanks!!!
You really have a Coder Eye haha
Even I white out my message you still could see!! xD

**Comment by hanliudeepmind** [comment]
Hello, Sorry for come again ><
since I succeed to use this method, I only use it for not to 1 day
but then my new created outlook mail seems be blocked xD

![image](https://user-images.githubusercontent.com/111733657/186798814-b82bfe23-dd2d-4da6-a1c4-1633fb576482.png)

maybe outlook or hotmail is not a good choice@@

**Comment by soranoo** [comment]
The new core has under development, I hope that will help to decrease account lock/ban.

**Comment by hanliudeepmind** [comment]
Thank you!!

I just want to remind other ppl if they want to use it they should create a new mail better!

Professor Soranoo's method is so nice with only a little bit delay about 2 second, I think it's not a big deal.

But if one need for webhook signal without any delay could buy tv plan when Black Friday discount(about 2022/11/25) for 40～60% off.

Anyway, thank your for give us a choice to use webhook for free tv plan!!!!
I am looking forward to the new core one!!!🥺🙇🏻‍♂️

**Comment by soranoo** [comment]
A new update has been released.
